buildCosts:
  cities:
    town:
      stone: 20
      arable_land: 30
    city:
      stone: 300
      arable_land: 400
    metropolis:
      stone: 500
      arable_land: 700

expansionTarget:
  cost:
    stone: 20
    arable_land: 10
  duration: 100

cellDesirabilityBonus:
  bonusMultiplier: 1000
  adjacentWeight: 40

population:
  maxPerTerritory: 100
  cityBonus: 500
  growthRate: 0.02

resource:
  baseYield: 1

resourceGroups:
  Water:
    - fresh_water
  Minerals:
    - iron_ore
    - precious_metals
    - gems
    - stone
    - copper_ore
    - salt
  Food:
    - fish
    - wild_fruits
    - game_animals
    - grazing_animals
  Agriculture:
    - fertile_soil
    - arable_land
    - pastures
  Flora:
    - medicinal_plants
    - timber
    - date_palm
    - fur_animals
    - herbs

resourceWeights:
  fresh_water: 1
  stone: 1
  copper_ore: 2
  iron_ore: 3
  salt: 4
  precious_metals: 8
  gems: 10
  wild_fruits: 1
  fish: 10
  game_animals: 15
  grazing_animals: 30
  fertile_soil: 1
  arable_land: 2
  pastures: 3
  herbs: 1
  medicinal_plants: 2
  date_palm: 3
  timber: 4
  fur_animals: 5

territoryMaintenance:
  costs:
    Water: 1
    Minerals: 0
    Food: 2
    Agriculture: 1
    Flora: 1
  expansionMultiplier: 5
